apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app-{{ .Values.myVar1 }}-{{ .Values.myVar2 }}
  namespace: argocd
  {{ .Values }}
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - ../../test-app/values/child-values.yaml
    path: test-app/grandchild
    repoURL: https://github.com/kavishdahekar/argocd-tutorial
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
