apiVersion: v1
kind: Pod
metadata:
  name: whalesay-{{ .Values.myVar1 }}-{{ .Values.myVar2 }}
  namespace: argocd
spec:
  containers:
  - name: whalesay
    image: docker/whalesay
    imagePullPolicy: "IfNotPresent"
    command: ["cowsay","Hello Alex"]