apiVersion: v1
kind: Pod
metadata:
  name: whalesay
  namespace: argocd
  labels:
    myVar1: {{ .Values.myVar1 }}
    myVar2: {{ .Values.myVar2 }}
spec:
  containers:
  - name: whalesay
    image: docker/whalesay
    imagePullPolicy: "IfNotPresent"
    command: ["cowsay","Hello Alex"]